server:
  port: 9376
spring:
  mvc:
    static-path-pattern: /image/**
  datasource:
#    url: jdbc:mysql://39.106.116.16:3306/bise?serverTimezone=UTC
    url: jdbc:mysql://82.157.247.91:3306/bise?serverTimezone=UTC
    username: bise
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  web:
    resources:
      static-locations: file:./image/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true